-- 코드를 작성해주세요
# select year(DIFFERENTIATION_DATE) YEAR,
#     (select max(SIZE_OF_COLONY)
#     from ECOLI_DATA
#     where YEAR = YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY YEAR_DEV,
#     id
# from ECOLI_DATA 
# order by year asc, year_dev

SELECT YEAR(e1.DIFFERENTIATION_DATE) AS YEAR,
       m.MAX_SIZE - e1.SIZE_OF_COLONY AS YEAR_DEV,
       e1.ID
FROM ECOLI_DATA e1
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
           MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) m
ON YEAR(e1.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;